# Use the official ASP.NET Core image as the base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the official .NET SDK image for build and publish
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies
COPY ["./Wesley.bff/Server/Wesley.bff.Server.csproj", "./"]
RUN dotnet restore "Wesley.bff.Server.csproj"

# Copy the rest of the application code
COPY . .

# Build the application
RUN dotnet build "Wesley.bff.Server.csproj" -c Release -o /app/build

# Publish the application
RUN dotnet publish "Wesley.bff.Server.csproj" -c Release -o /app/publish

# Final stage: Copy the published app to the base image and set up the entry point
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

# Set the entry point to run the application
ENTRYPOINT ["dotnet", "Wesley.bff.Server.dll"]
